#!/bin/bash

# Won't let the script run, if ran as root
if [ "$EUID" -ne 0 ]; then
    echo "Use sudo to run this script"
    exit 1
fi

# clones the repo, which includes all the starting files that the user needs.
git clone https://gitlab.com/cit2420/2420-as2-starting-files

# File with package list
# the variable file now is assigned to the .txt file was included in the project1 folder.
file="install-packages.txt"

# Read and install each package on the text file
# pacman is our package manager for Arch Linux
# -S is used to sync our packages, --noconfirm so that the user does not have to answer any prompts during the installation process
# < $file is being used to specify that pacman will read through our variable which includes the install-packages and install them accordingly.
pacman -S --noconfirm - < $file
