#!/bin/bash

# checks if the script is being run using sudo
if [ "$EUID" -ne 0 ]; then
    echo "Use sudo to run this script"
    exit 1
fi

# create a symbolic link between the users starting file repo that has been cloned.
# connects it to the ~/bin which is the user's local machine bin, here it will automatically create the folders which are needed. Allowing the user to access them in their bin on their localmachine
ln -s /home/$USER/2420-as2-starting-files/bin ~/bin

# creates a symbolic link between the user's starter files to the local machine .config so that the user can access them there. If you do not have .config created it will create it for you.
ln -s /home/$USER/2420-as2-starting-files/config ~/.config

# creates a symbolic link between user's bashrc that is installed through the starting files and their local machine ./bashrc, even if they do not have this created. It will create .bashrc for you
ln -s /home/$USER/2420-as2-starting-files/home/bashrc ~/.bashrc
